apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: jk-create-react-app-typescript-app-server
    http:
      paths:
      - backend:
          serviceName: app-service
          servicePort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: ts
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ts
  template:
    metadata:
      labels:
        app: ts
    spec:
      containers:
      - image: jk-create-react-app-typescript
        name: jk-create-react-app-typescript
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        ports:
        - containerPort: 8080
